backend:
  name: github
  repo: tw1720/blog
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://free.is-cool.dev
  auth_endpoint: /api/auth
media_folder: static/images
public_folder: /images
collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "Y-MM-DDThh:mm:ssZ"}
      - { label: 'Categories', name: 'categories', widget: 'string', required: false }
      - { label: "Tags", name: "tags", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false, required: false  }
      # - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false  }
      - { label: 'Body', name: 'body', widget: 'markdown' }
